[features]
seeds = false
[programs.devnet]
marketplace_aas = "22YCvsiJSir1Hb7ihcTvGGXg9uA84AfYjN6vsqphkuEx"
p2p_trading = "EMihg7zqtS6aWKc6K4qRKsjAPJbfhnJpGLakjgb3xvvP"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/braeden/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
